---
# Inventário para ambiente Single Instance + ASM (Data Guard)
# primary = banco primário | standby = banco standby

all:
  children:
    si_nodes:
      hosts:
        oracle-primary:
          ansible_host: 192.168.56.201
          ansible_user: root
          oracle_hostname: oracle-primary
          oracle_sid: ORCL
          dg_role: PRIMARY

        oracle-standby:
          ansible_host: 192.168.56.202
          ansible_user: root
          oracle_hostname: oracle-standby
          oracle_sid: ORCL
          dg_role: PHYSICAL_STANDBY

    si_primary:
      hosts:
        oracle-primary:

    si_standby:
      hosts:
        oracle-standby:

  vars:
    # Interface de rede
    public_interface: enp0s3

    # Discos ASM (cada VM tem seus próprios discos — não compartilhados)
    asm_data_disks:
      - /dev/sdb    # DATA disk 1
      - /dev/sdc    # DATA disk 2

    asm_fra_disks:
      - /dev/sdd    # FRA disk 1

    # Modo Single Instance
    oracle_install_type: SI
